### ISSUE TITLE
More Mockups in Sketch or Google Present 

### ISSUE THREAD

**Issue by morisy** [MuckRock/cfb#1]
[Here is the current current Mockup](https://docs.google.com/presentation/d/1lDs08aFUQXW5zh1NrroMiJj1x8kM9Zb01X5iCGK8EL0/edit#slide=id.p).

**Comment by thecristen** [comment]
@harrislapiroff made a Sketch mockup!

![](https://files.slack.com/files-pri/T0556DP9Y-FFZ0VQSUC/desktop.png)

**Comment by whoback** [comment]
Closing as we have a design team now and newer mocks to work from.
