### ISSUE TITLE
begin exploring DB updates via API rather than manual script process

### ISSUE THREAD

**Issue by whoback** [MuckRock/cfb#13]

**Comment by dskrvk** [comment]
The plan is to have a scheduled script that repopulates the DB from the API every 15 minutes. See https://github.com/MuckRock/cfb/pull/46

**Comment by dskrvk** [comment]
Works now as a scheduled job every 10 minutes (there was no option for every 15):

> &gt; heroku logs -a cfb-mr -d scheduler

> 2019-04-07T22:11:50.342644+00:00 heroku[scheduler.8847]: Starting process with command `python3 create_db.py`
> ...
> 2019-04-07T22:11:54.323506+00:00 app[scheduler.8847]: db initialized
> 2019-04-07T22:11:55.078733+00:00 app[scheduler.8847]: got a batch of 41 results
> 2019-04-07T22:11:55.250199+00:00 app[scheduler.8847]: 1 rows imported so far
> ...
> 2019-04-07T22:12:11.019522+00:00 app[scheduler.8847]: 35 rows imported so far
> 2019-04-07T22:12:11.019908+00:00 app[scheduler.8847]: 35 eligible rows imported out of 41
> 2019-04-07T22:12:11.180889+00:00 heroku[scheduler.8847]: State changed from up to complete
> 2019-04-07T22:12:11.162808+00:00 heroku[scheduler.8847]: Process exited with status 0

We still need to fix https://github.com/MuckRock/cfb/issues/29
