### ISSUE TITLE
Finalize DB fields and copy by Feb. 3

### ISSUE THREAD

**Issue by morisy** [MuckRock/cfb#3]
[Current fields here](https://www.muckrock.com/assignment/submit-your-foia-suggestion-122/#assignment-responses). If you have permissions, you'll be able to see admin interface; otherwise, will kick you to just being able to enter new entries.

If you'd like fields changed or copy updated, leave comments here. Copy can be tweaked pretty much up until the end. Fields, however, need to be locked down by Feb. 3 and will be a pain (but not quite impossible) to change after this weekend.

**Comment by morisy** [comment]
I think it would be good to have an explicit public citation field, allowing for a hyperlink back to a publication that submitted. That can kind of be inferred by username of submitter, but this allows that to be an explicit choice + more credit with a link back to the person, rather than just their MuckRock profile

**Comment by whoback** [comment]
Here are the DB fields being pulled from the script that @morisy put together:
`db_fields = (
            "id",
            "crowdsource",
            "user",
            "edit_user",
            "data",
            "datetime",
            "edit_datetime",
            "tags",
            "number",
            "flag",
            "gallery",
            "name", 
            "description", 
            "tips", 
            "links",
            "sample_request", 
            "author")`

What are we missing?
According to our discussion we won't need `number` or `flag` or `crowdsource` fields.
