### ISSUE TITLE
Create a friendly error page

### ISSUE THREAD

**Issue by dskrvk** [MuckRock/cfb#31]
This should be a static page displayed if a request processing failed due to an error (other than 404) and should not contain any internal information, just a generic friendly error message.

**Comment by whoback** [comment]
I've added a 500 page to the app. Can you think of anything else that should be included? We can do a more global exception handler if thats what you had in mind?

As it stands right now there are a few things happening:
1. 404s are being handled on main requests `muck.rocks/notarequest` by a bare bones 404 page `404.html`
2.  if an actual request doesn't exist in the db such as `muck.rocks/request/500` the server returns a 200 status and the template displays some 404 text which we should change. See `base.html` near line 30.

**Comment by dskrvk** [comment]
Exactly, a default exception handler to make sure we don't accidentally spit out an exception trace at the user. I suppose if the application crashes catastrophically only the webserver would be able to handle errors. Once we have that going we can configure the same 500.html at the webserver level.

**Comment by thecristen** [comment]
fixed in #44
