### ISSUE TITLE
Examples of Similar Sites for Inspiration

### ISSUE THREAD

**Issue by morisy** [MuckRock/cfb#4]
Add single-purpose sites below for design/UX inspiration.

**Comment by morisy** [comment]
[NSFW Oberlin Fan Site](http://whythefuckshouldichooseoberlin.com)

**Comment by morisy** [comment]
[Barack Obama is Your New Bicycle](http://barackobamaisyournewbicycle.com), which was definitely of An Era.

**Comment by ryan10** [comment]
[Consulting Random Work Generator](http://www.consultingrandomworkgenerator.com)

**Comment by ryan10** [comment]
[The F***ing Weather (NSFW)](http://thefuckingweather.com/)

**Comment by whoback** [comment]
@morisy what are your thoughts on URL routes? There are a few different examples in use here:

1. Obama/Oberlin: same URL content changes on reload
2. Consulting: memes are tied to UIDs which allow for permalinks
3. Typical blog: URLs tied to `title` or some other `slug` example: `/my-cool-foia-request.html`

**Comment by ryan10** [comment]
Options 2 or 3 seem more shareable to me!

**Comment by morisy** [comment]
Excellent question. Oberlin has URLs you can get if you use the social share buttons or click the permalink icon, like:

'''http://whythefuckshouldichooseoberlin.com/2099/'''

So if you just refresh on the homepage it keeps the base URL, but then if you click one of those share buttons/permalink then you get that long URL, and that doesn't change if you refresh, but you still have the "show me another reason" button so you don't get stuck on that page. I think that approach generally could work well, but for SEO/discoverability/readability I think ending with /my-cool-foia-request-123 could be a good approach
