### ISSUE TITLE
Permalink feature / Example of variable routing

### ISSUE THREAD

**Issue by whoback** [MuckRock/cfb#8]
We were talking about how to have permalinks in our BE discussion last night. 

See documentation: http://flask.pocoo.org/docs/1.0/quickstart/#routing 

Thinking we can use a form of this example:

```
@app.route('/post/<int:post_id>')
def show_post(post_id):
    # show the post with the given id, the id is an integer
    return 'Post %d' % post_id
```

Some points to keep in mind / discuss:

- SEO since these are essentially dynamic links and not linked from anywhere / crawled 
- 404 pages in general and when using this method how to handle requests that aren't in our DB :: if we have 365 examples in DB what happens when someone hits `muck.rock/1234`

**Comment by whoback** [comment]
@egfrank your initial rev gets us pretty far! How would you like to handle the situation when we're querying the db for a row that doesn't exist like `select_id(451)` 

Things I can think of:
- We can add a `SELECT COUNT (*)` query and store a variable with that number and then 404 any IDs > than that variable
- We could make use of the templating like you have in `base.html` using `if item` I'm not 100% on how this would work but def doable
- We can hard code (if we decide to limit to 365) our select query but this is a Q for @morisy

**Comment by egfrank** [comment]
This is similar to bullet #2 but I think in `routes.py` we can do 
```
item = select_id(451)
if item == None:
    return redirect(404)
else:
    return url_for("request/451")
```
obviously that's not the exact code but I think that works?

I also like bullet #1 unless it's slowing stuff down- when would we actually be running that query & updating the variable? When we update the database with the CRON job? Or like when we actually get the request for `muck.rocks/451` ?
